/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etapa03guia01ejercicio04;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author calga
 */
public class BusquedaPorPrecio extends javax.swing.JInternalFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form BusquedaPorPrecio
     */
    public BusquedaPorPrecio() {
        initComponents();
        armarColumna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResultado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jHasta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        label1.setText("label1");

        jtResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtResultado);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Entre $:");

        jDesde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDesdeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("y");

        jHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHastaActionPerformed(evt);
            }
        });
        jHasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jHastaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("BUSCAR POR PRECIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDesdeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDesdeKeyReleased
        // TODO add your handling code here:
        borrarFila();
        jHastaKeyReleased(evt);
        double desde=0;
        double hasta=0;
        try{
        desde = Double.parseDouble(jDesde.getText());
        }catch (NumberFormatException e){
            hasta = 999999999;
         }
            for (Productos elProducto : Menu.listado) {
            if (elProducto.getPrecio()> desde && elProducto.getPrecio()< hasta) {
                 modelo.addRow(new Object[]{
                elProducto.getCodigo(),elProducto.getRubro(),
                elProducto.getPrecio(),elProducto.getStock(),elProducto.getDescripcion()
            });
            }
        }

        
    }//GEN-LAST:event_jDesdeKeyReleased

    private void jHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHastaActionPerformed

    private void jHastaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jHastaKeyReleased
        // TODO add your handling code here:
         borrarFila();
//         jHastaKeyReleased(evt);
//        double desde=0;
//        double hasta=0;
//        try{
//        hasta = Double.parseDouble(jHasta.getText());
//        }catch (NumberFormatException e){
//            desde= 0;
//         }
//            for (Productos elProducto : Menu.listado) {
//            if (elProducto.getPrecio()> desde && elProducto.getPrecio()< hasta) {
//                 modelo.addRow(new Object[]{
//                elProducto.getCodigo(),elProducto.getMarca(),elProducto.getRubro(),
//                elProducto.getPrecio(),elProducto.getStock(),elProducto.getDescripcion()
//            });
//            }
//        }

        
     
    }//GEN-LAST:event_jHastaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDesde;
    private javax.swing.JTextField jHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtResultado;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
private void armarColumna(){
    modelo.addColumn("Código");
    modelo.addColumn("Categoria");
    modelo.addColumn("Precio");
    modelo.addColumn("Stock");
    modelo.addColumn("Descripción");
    jtResultado.setModel(modelo);
}

private void borrarFila(){
int fila = jtResultado.getRowCount()-1;
    for (int i = fila; i >= 0; i--) {
        modelo.removeRow(i);
    }
   
}
}
